blog/urls.py
from django.conf.urls import url
from blog.models import Post
from blog.views import PostLV, PostDV
from django.views.generic import ListView, DetailView


urlpatterns = [
    url(r'^$', PostLV.as_view(), name='index'),
    url(r'^post/$', PostLV.as_view(), name='post_list'),
    url(r'^post/(?P<pk>\d+)/$', PostDV.as_view(), name='post_detail'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^soaka/', include('soaka.urls', namespace='soaka')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace='blog')),
]

soaka/urls.py
from django.conf.urls import url
from soaka import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>\d+)/$', views.detail, name='detail'),
    url(r'^(?P<question_id>\d+)/results/$', views.results, name='results'),
    url(r'^soaka/(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
]

blog/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

# Create your models here.

@python_2_unicode_compatible

class Post(models.Model):
    title = models.CharField('TITLE', max_length=50)
    content = models.TextField('CONTENT')
    create_date = models.DateTimeField('Create Date', auto_now_add=True)
    modify_date = models.DateTimeField('Modify Date', auto_now=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'my_post'
        ordering = ('-create_date',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.pk,))

    def get_previous_post(self):
        return self.get_previous_by_modify_date()

    def get_next_post(self):
        return self.get_next_by_modify_date()

soaka/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

blog/views.py
from django.views.generic import ListView, DetailView
#from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
#from django.views.generic.dates import DayArchiveView, TodayArchiveView
from django.shortcuts import render
from blog.models import Post

# Create your views here.

class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 10

class PostDV(DetailView):
    model = Post

'''
class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_date'

class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_date'
    make_object_list = True

class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_date'

class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_date'

class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_date'
'''

soaka/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from soaka.models import Choice, Question

# Create your views here.

def index(request):
    latest_question_list = Question.objects.all().order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list }
    return render(request, 'soaka/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'soaka/detail.html', {'question': question})

def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'soaka/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice_votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('soaka:results', args=(p.id,)))

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'soaka/results.html', {'question': question})

blog/templates/blog/post_all.html
<!DOCTYPE html>
<html>
<head>
    <title>Simple Board</title>
</head>

<body>
    <table id="board" cellspacing=1 width="80%" align=center border=1>
        <tr>
            <td width="10%"><p align=center>number</p></td>
            <td width="60"><p align=center>subject</p></td>
            <td width="15"><p align=center>create date</p></td>
            <td width="15"><p align=center>modify date</p></td>
        </tr>

        {% for post in posts %}
            <tr>
                <td width="10%"><p align=center>{{ post.id }}</p></td>
                <td width="60%"><p align=center><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></p></td>
                <td width="15%"><p align=center>{{ post.create_date|date:"Y.N.d" }}</p></td>
                <td width="15%"><p align=center>{{ post.modify_date|date:"Y N d" }}</p></td>
            </tr>
        {% endfor %}

<br/>

        <div>
            <span>
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">PreviousPage</a>
                {% endif %}

                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">NextPage</a>
                {% endif %}
            </span>
        </div>
</body>
</html>

blog/templates/blog/post_detail.html
<h2>{{ object.title }}</h2>

<p class="other_posts">
    {% if object.get_previous_by_modify_date %}
    <a href="{{ object.get_previous_post.get_absolute_url }}" title="View previous post"> &laquo;--{{ object.get_previous_post }}</a>
    {% endif %}

    {% if object.get_next_by_modify_date %}
    | <a href="{{ object.get_next_post.get_absolute_url }}" title="View next post">{{ object.get_next_post }}--&raquo;</a>
    {% endif %}
</p>

<p class="date">{{ object.modify_date|date:"j F Y" }}</p>
<br/>

<div class="body">
    {{ object.content|linebreaks }}
</div>

soaka/templates/soaka/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message}}</strong></p>{% endif %}

<form action="{% url 'soaka:vote' question_id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

soaka/templates/soaka/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/soaka/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>

{% else %}
    <p>No polls are available.</p>
{% endif %}

soaka/templates/soaka/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'soaka:detail' question.id %}">Vote again?</a>

templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
<title>{% block title %}Django Web Programming{% endblock %}</title>

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "css/base.css" %}{% endblock %}" />
<link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />

</head>

<body>

<div id="header">
    <h2 class="maintitle">Easy&amp;Fast Django Web Programming</h2>
    {% if user.is_active %}
    <h4 class="welcome">Welcome,
                <strong>{% firstof user.get_short_name user.get_username %}</strong> /
                <a href="{% url 'password_change' %}">Change Password</a> /
                <a href="{% url 'logout' %}">Logout</a>
    </h4>
    {% else %}
    <h4 class="welcome">Welcome, Anonymous /
                <a href="{% url 'login' %}">Login</a> /
                <a href="{% url 'register' %}">Register</a>
    </h4>
    {% endif %}
</div>

<div id="menu">
    <li><a href="{% url 'home' %}">Home</a></li>
    <li><a href="{% url 'bookmark:index' %}">Bookmark</a></li>
    <li><a href="{% url 'blog:index' %}">Blog</a></li>
    <li><a href="{% url 'photo:index' %}">Photo</a></li>

    <li>Add&bigtriangledown;
        <ul>
            <li><a href="{% url 'bookmark:add' %}">Bookmark</a></li>
            <li><a href="{% url 'blog:add' %}">Post</a></li>
            <li><a href="#">Photo</a></li>
        </ul>
    </li>
    <li>Change&bigtriangledown;
        <ul>
            <li><a href="{% url 'bookmark:change' %}">Bookmark</a></li>
            <li><a href="{% url 'blog:change' %}">Post</a></li>
            <li><a href="#">Photo</a></li>
        </ul>
    </li>

    <li><a href="{% url 'blog:post_archive' %}">Archive</a></li>
    <li><a href="{% url 'blog:search' %}">Search</a></li>
    <li><a href="{% url 'admin:index' %}">Admin</a></li>
</div>

{% block content %}{% endblock %}

{% block footer %}{% endblock %}

</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}home.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/home.css" %}{% endblock %}

{% block content %}

<div id="content_home">

    <div id="homeimg">
        <a href="/"><img src="{% static 'img/mainimg.jpg' %}" style="height:256px;"/></a>
        <h4 style="margin: 0;">This is Django powered web site.</h4>
    </div>

    <hr style="margin: 5px 0;">
   
    <h2>Select Application</h2>

    <table id="applist">
        <tr>
        <td><b><i><a href="{% url 'bookmark:index' %}">Bookmark</a></i><b></td>
        <td>You can write your own post and share to others. Donec id elit non miporta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo</td>
        <td class="Edit"><i><a href"#">Add</a></i></td>
        <td class="Edit"><i><a href"#">Change</a></i></td>
        </tr>

        <tr>
        <td><b><i><a href="{% url 'blog:index' %}">Blog</a></i><b></td>
        <td>You can write your own post and share to others. Donec id elit non miporta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo</td>
        <td class="Edit"><i><a href"#">Add</a></i></td>
        <td class="Edit"><i><a href"#">Change</a></i></td>
        </tr>

        <tr>
        <td class="Edit"><i><a href"#">Photo</a></i></td>
        <td>You can write your own post and share to others. Donec id elit non miporta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo</td>
        <td class="Edit"><i><a href"#">Add</a></i></td>
        <td class="Edit"><i><a href"#">Change</a></i></td>
        </tr>
    </table>
</div>
{% endblock content %}

{% block footer %}
<div id="footer">
    &copy; eonsu 2016
</div>
{% endblock footer %}